baseURL = '/'
languageCode = 'en-us'
title = 'The Infinite Unknown'
disqusShortname = "jaredwatkins"
enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-12506512-2" # Optional, add tracking Id for analytics

[Params]
  customcss = ["css/custom.css"]  
  show_menu = true # Optional, set false to disable menu entirely
  powered_by = false # Optional, set false to disable theme credits
  # mainroad theme options
  opengraph = true
  authorbox = false
  post_navigation = true
  schema = true
  twitter_cards = true
  readmore = true
  pager = true
  mainSections = ["post", "projects", "news"]
  dateformat = "2006-01-02"
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700"


[Author]
  name = "Jared Watkins"
  bio = ""
  avatar = ""

[permalinks]
  post = "/:year/:month/:title/"

[Params.sidebar]
  home = "right"
  kust = "left"
  single = false
  widgets = ["search", "recent", "categories", "social", "tagcloud"]

[Params.widgets]
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget

[Params.widgets.social]
  twitter = "theOtherJared"
  github = "jimmydigital"

[Params.widgets.search]
  url = "https://google.com/search"
  input.name = "sitesearch"
  input.pre = ""

[imaging]
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter = "box"

  # Default JPEG quality setting. Default is 75.
  quality = 75

  # Anchor used when cropping pictures.
  # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
  # Smart Cropping is content aware and tries to find the best crop for each image.
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor = "smart"

[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Projects"
    weight = 4
    identifier = "project"
    url = "/projects/"
  [[menu.main]]
    name = "Tags"
    weight=4
    identifier = "tags"
    url = "/tags"

[markup.goldmark.renderer]
unsafe= true

[module]
  [[module.imports]]
    # Paths are protocol-relative, meaning they should NOT start with http[s]://
    path = "github.com/Vimux/Mainroad" # Project theme
    disable = false
  [[module.imports]]
    path = "github.com/rootwork/hugo-module-gallery-grid"

  [[module.mounts]]
    source = "site/content" # Project content
    target = "content"
  [[module.mounts]]
    source = "site/static" # Project static assets
    target = "static"

