#!/usr/bin/env sh
set -e

hugo  --configDir config-texify3 --cleanDestinationDir --gc --logLevel info

read -p "Press [Enter] key to publish to S3..."

cd public
aws s3 sync . s3://jaredwatkins.com/ --delete

