#!/usr/bin/env sh
set -e

hugo  --configDir config-texify3 --cleanDestinationDir --gc --logLevel info
rm -rf static/pagefind
npm run index
hugo  --configDir config-texify3 --cleanDestinationDir --gc --logLevel info

read -p "Press [Enter] key to publish to S3..."

cd public
aws s3 sync . s3://jaredwatkins.com/ --delete

cd ..
aws cloudfront create-invalidation --distribution-id ER0YCKLM2ZTMA --paths "/*"

