%%{init: {"theme": "base", "themeVariables": {"fontSize": "14px"}}}%%
xychart-beta
    title "Hours Per Year Consumed by Car Ownership (Earning + Driving)"
    x-axis ["1973", "1983", "1993", "2003", "2013", "2023", "2026"]
    y-axis "Hours per year" 0 --> 900
    bar [711, 750, 731, 728, 765, 739, 706]
    line [455, 470, 427, 399, 448, 428, 396]
