%%{init: {"theme": "base", "themeVariables": {"fontSize": "14px"}}}%%
xychart-beta
    title "New Car Price as Multiple of Median Household Income (1973-2026)"
    x-axis ["1973", "1983", "1993", "2003", "2013", "2023", "2026"]
    y-axis "Price / Income ratio" 0.0 --> 0.80
    bar [0.38, 0.43, 0.43, 0.48, 0.59, 0.61, 0.59]
    line [0.38, 0.43, 0.43, 0.48, 0.59, 0.61, 0.59]
